create database day13;
use day13;
create table product(pname varchar(40),pprice float,pcost float,pqty int,ptype varchar(40));
CREATE TABLE t3(id INT );
CREATE TABLE t4 (id INT );
INSERT INTO t1 VALUES (1),(2),(3);
INSERT INTO t2 VALUES (2),(3),(4);

CREATE TABLE t1 (id INT PRIMARY KEY);
CREATE TABLE t2 (id INT PRIMARY KEY);
INSERT INTO t1 VALUES (1),(2),(3);
INSERT INTO t2 VALUES (2),(3),(4);
INSERT INTO t1 VALUES (5);
INSERT INTO t2 VALUES (5);
desc t2;
SELECT id FROM t1 UNION SELECT id FROM t2;
SELECT id FROM t1 UNION ALL SELECT id FROM t2;
(SELECT id FROM t1) INTERSECT (SELECT id FROM t2);
select round(52.4567,1);
select tan(45);
select pi();
select pow(1);
SELECT 'MySQL ' 'Fss ' 'Concatenation';
SELECT INSTR('fss1 INSTR', 'fss1');
SELECT INSTR('fs INSTR', 'fs');
SHOW CHARACTER SET;
SET @s = CONVERT('MySQL String Length' USING ucs2);
SELECT CHAR_LENGTH(@s), LENGTH(@s);
select char_length(trim(' SaiAnnapareddy'));
SELECT LEFT('Sai333 Annapareddy', 18);
SELECT LOWER('MySQL');
show tables;
use sales;
select * from product;
insert into product values(112,'Iad',5000,10,null,'C');
alter table product;
update product set pcost=pprice*pqty order by ptype;
set sql_safe_updates=0;
UPDATE product 
SET pname = REPLACE(pname,'Ipad','Tablet');
create table names1(first_name varchar(50),last_name varchar(50));
insert into names1 values('jayachandra','reddy');
select * from names1 where last_name like '%y';
select upper('annapareddy');
show databases;
use sales;
create table conn(s1 varchar(10),s2 varchar(10),result varchar(20));